# Generated by Django 3.2.5 on 2021-10-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsubscribers',
            name='owner',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='ow_ip', to='users.users', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='postsubscribers',
            name='user',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='us_ip', to='users.users', verbose_name='Заявка'),
        ),
    ]
