# Generated by Django 3.2.5 on 2021-10-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.Users', verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Такой URL уже существует!!!'}, max_length=40, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='published',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='main.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='published',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Такой URL уже существует!!!'}, max_length=40, unique=True, verbose_name='URL'),
        ),
    ]
