# Generated by Django 3.2.5 on 2021-10-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211018_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_set', to='main.published', verbose_name='Публикация'),
        ),
    ]
